name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ secrets.FRONTEND_URL }}   # This is the link that will show on GitHub
    steps:
      - name: Curl backend + frontend
        run: |
          echo "Pinging backend..."
          curl -sS "${{ secrets.BACKEND_URL }}"/status || true

          echo "Pinging frontend..."
          curl -sS "${{ secrets.FRONTEND_URL }}" || true
